# ---------------------------------------------------------------------------
# Site bucket
#
# Phase 7 served this bucket directly over the S3 website endpoint with a
# public-read policy. Phase 8 took that away: the bucket is private again and
# the only thing allowed to read it is the CloudFront distribution, via the
# Origin Access Control in cloudfront.tf.
#
# Note there is no aws_s3_bucket_website_configuration any more. Website
# hosting and OAC are mutually exclusive — OAC signs requests to the REST
# endpoint, which does not implement index/error document rules. CloudFront
# covers that with default_root_object and custom_error_response instead.
# ---------------------------------------------------------------------------

resource "aws_s3_bucket" "frontend" {
  bucket = "${var.project_name}-${var.environment}-site-${data.aws_caller_identity.current.account_id}"
}

resource "aws_s3_bucket_public_access_block" "frontend" {
  bucket = aws_s3_bucket.frontend.id

  block_public_acls       = true
  block_public_policy     = true
  ignore_public_acls      = true
  restrict_public_buckets = true
}

resource "aws_s3_bucket_server_side_encryption_configuration" "frontend" {
  bucket = aws_s3_bucket.frontend.id

  rule {
    apply_server_side_encryption_by_default {
      sse_algorithm = "AES256"
    }
  }
}

# The AWS:SourceArn condition is what stops any other CloudFront distribution
# in any other account from using this bucket as an origin. Without it, the
# cloudfront.amazonaws.com principal is effectively "all of CloudFront".
resource "aws_s3_bucket_policy" "frontend_oac" {
  bucket = aws_s3_bucket.frontend.id

  policy = jsonencode({
    Version = "2012-10-17"
    Statement = [
      {
        Sid    = "AllowCloudFrontRead"
        Effect = "Allow"
        Principal = {
          Service = "cloudfront.amazonaws.com"
        }
        Action   = "s3:GetObject"
        Resource = "${aws_s3_bucket.frontend.arn}/*"
        Condition = {
          StringEquals = {
            "AWS:SourceArn" = aws_cloudfront_distribution.frontend.arn
          }
        }
      }
    ]
  })
}

# ---------------------------------------------------------------------------
# Locals
# ---------------------------------------------------------------------------

locals {
  frontend_dir = "${path.module}/../../frontend"

  # Origins allowed to call the API and to PUT to the raw bucket. Browsers
  # match these byte-for-byte: scheme, host and port must all line up.
  #
  # As of Phase 8 the site is served from CloudFront over HTTPS, so the old
  # http://...s3-website... origin is gone. Anything still pointing at it will
  # fail CORS — that is expected, the website endpoint no longer exists.
  # The *.cloudfront.net origin stays allowed even once a custom domain exists,
  # so the site keeps working while DNS propagates and as a fallback if the
  # delegation is ever broken.
  frontend_origins = concat(
    ["https://${aws_cloudfront_distribution.frontend.domain_name}"],
    [for name in local.all_domain_names : "https://${name}"],
    var.local_dev_origins,
    var.extra_frontend_origins,
  )

  # Static assets uploaded verbatim. config.js is generated below instead,
  # so the stack's real IDs are never hand-copied into the repo.
  frontend_static_files = {
    "index.html" = "text/html"
    "styles.css" = "text/css"
    "app.js"     = "application/javascript"
  }

  frontend_config_js = <<-EOT
    /* GENERATED BY TERRAFORM — do not edit by hand.
     * Source of truth: infra/terraform/frontend.tf
     *
     * These are public identifiers. The Cognito app client has no secret and
     * the API is protected by the JWT authorizer, not by hiding these values.
     */
    window.APP_CONFIG = {
      region: "${var.aws_region}",
      apiBaseUrl: "${aws_apigatewayv2_api.http_api.api_endpoint}",
      userPoolId: "${aws_cognito_user_pool.main.id}",
      userPoolClientId: "${aws_cognito_user_pool_client.app_client.id}",
      maxUploadBytes: ${var.max_upload_bytes}
    };
  EOT
}

# ---------------------------------------------------------------------------
# Upload the site
#
# content_type is set explicitly because S3 defaults every object to
# binary/octet-stream, which makes the browser download index.html instead of
# rendering it. etag triggers re-upload whenever a file changes on disk, and
# also feeds the CloudFront invalidation trigger.
#
# cache_control is read by the CachingOptimized policy at the edge, so these
# values control CDN behaviour as well as browser behaviour.
# ---------------------------------------------------------------------------

resource "aws_s3_object" "frontend_static" {
  for_each = local.frontend_static_files

  bucket        = aws_s3_bucket.frontend.id
  key           = each.key
  source        = "${local.frontend_dir}/${each.key}"
  content_type  = "${each.value}; charset=utf-8"
  etag          = filemd5("${local.frontend_dir}/${each.key}")
  cache_control = each.key == "index.html" ? "no-cache" : "public, max-age=300"
}

resource "aws_s3_object" "frontend_config" {
  bucket        = aws_s3_bucket.frontend.id
  key           = "config.js"
  content       = local.frontend_config_js
  content_type  = "application/javascript; charset=utf-8"
  etag          = md5(local.frontend_config_js)
  cache_control = "no-cache"
}

# Mirror the generated config back into the repo so `python -m http.server`
# in frontend/ works against the live stack too. It is gitignored.
resource "local_file" "frontend_config" {
  filename = "${local.frontend_dir}/config.js"
  content  = local.frontend_config_js
}
